import React from "react";
import "./loader-generated.scss";

// this code is generated by third-party web-app
const Loader = () => (
  <div className="loadingio-spinner-spinner-5fprckgfxgg">
    <div className="ldio-on99k9onxu">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
);

export { Loader };
